#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate tcg/tci-direct-call.c.inc (write output to stdout)."""

import textwrap


def generate():
    print("""/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Generated by scripts/gen-tci-direct-call.py; do not edit by hand.
 * Direct helper dispatch for TCI on 32-bit hosts, avoiding a JS libffi call.
 * Signature: bits 0-1 return kind (0 void, 1 i32, 2 i64), bits 2-4 nargs,
 * bit 5+j set when argument j is 64-bit.
 *
 * Keep small, address-taken shards: one large switch becomes a pathological
 * Asyncify/TurboFan register-allocation problem. Each shard handles one
 * argument-width mask (at most 24 signatures). The indirect outer dispatch
 * also prevents the Wasm linker/optimizer from inlining them all back into
 * one function. These are ordinary, Asyncify-instrumented helper calls.
 */""")
    for mask in range(128):
        print(f"""
static bool __attribute__((noinline))
tci_direct_call_m{mask}(unsigned sig, void *f, uint64_t *a, uint64_t *ret)
{{
    switch (sig) {{""")
        for kind, result in enumerate(["void", "uint32_t", "uint64_t"]):
            for nargs in range(mask.bit_length(), 8):
                sig = kind | (nargs << 2) | (mask << 5)
                types = ["uint64_t" if mask & (1 << j) else "uint32_t"
                         for j in range(nargs)]
                args = [f"a[{j}]" if mask & (1 << j) else f"(uint32_t)a[{j}]"
                        for j in range(nargs)]
                proto = ", ".join(types) if types else "void"
                call = f"(({result} (*)({proto}))f)({', '.join(args)});"
                if kind:
                    call = "*ret = " + call
                print(f"    case {sig}:")
                print(textwrap.fill(call, width=80, initial_indent=" " * 8,
                                    subsequent_indent=" " * 12,
                                    break_long_words=False,
                                    break_on_hyphens=False))
                print("        return true;")
        print("""    default:
        return false;
    }
}""")
    print("""
static inline bool tci_direct_call(unsigned sig, void *f, uint64_t *a,
                                   uint64_t *ret)
{
    static bool (*const shards[])(unsigned, void *,
                                 uint64_t *, uint64_t *) = {""")
    for first in range(0, 128, 3):
        print("        " + ", ".join(f"tci_direct_call_m{i}"
                                     for i in range(first, min(first + 3, 128)))
              + ",")
    print("""    };
    unsigned mask = sig >> 5;

    if (mask >= sizeof(shards) / sizeof(shards[0])) {
        return false;
    }
    return shards[mask](sig, f, a, ret);
}""")


if __name__ == "__main__":
    generate()
